<?xml version="1.0" encoding="UTF-8" ?>
<Package name="TwitterSearch" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="app" src="html/css/app.css" />
        <File name="bootstrap.min" src="html/css/bootstrap.min.css" />
        <File name="search" src="html/images/search.png" />
        <File name="voice-default" src="html/images/voice-default.png" />
        <File name="bootstrap" src="html/css/bootstrap.css" />
        <File name="mdb" src="html/css/mdb.css" />
        <File name="mdb.min" src="html/css/mdb.min.css" />
        <File name="style" src="html/css/style.css" />
        <File name="Roboto-Bold" src="html/font/roboto/Roboto-Bold.eot" />
        <File name="Roboto-Bold" src="html/font/roboto/Roboto-Bold.ttf" />
        <File name="Roboto-Bold" src="html/font/roboto/Roboto-Bold.woff" />
        <File name="Roboto-Bold" src="html/font/roboto/Roboto-Bold.woff2" />
        <File name="Roboto-Light" src="html/font/roboto/Roboto-Light.eot" />
        <File name="Roboto-Light" src="html/font/roboto/Roboto-Light.ttf" />
        <File name="Roboto-Light" src="html/font/roboto/Roboto-Light.woff" />
        <File name="Roboto-Light" src="html/font/roboto/Roboto-Light.woff2" />
        <File name="Roboto-Medium" src="html/font/roboto/Roboto-Medium.eot" />
        <File name="Roboto-Medium" src="html/font/roboto/Roboto-Medium.ttf" />
        <File name="Roboto-Medium" src="html/font/roboto/Roboto-Medium.woff" />
        <File name="Roboto-Medium" src="html/font/roboto/Roboto-Medium.woff2" />
        <File name="Roboto-Regular" src="html/font/roboto/Roboto-Regular.eot" />
        <File name="Roboto-Regular" src="html/font/roboto/Roboto-Regular.ttf" />
        <File name="Roboto-Regular" src="html/font/roboto/Roboto-Regular.woff" />
        <File name="Roboto-Regular" src="html/font/roboto/Roboto-Regular.woff2" />
        <File name="Roboto-Thin" src="html/font/roboto/Roboto-Thin.eot" />
        <File name="Roboto-Thin" src="html/font/roboto/Roboto-Thin.ttf" />
        <File name="Roboto-Thin" src="html/font/roboto/Roboto-Thin.woff" />
        <File name="Roboto-Thin" src="html/font/roboto/Roboto-Thin.woff2" />
        <File name="default-skin" src="html/img/lightbox/default-skin.png" />
        <File name="default-skin" src="html/img/lightbox/default-skin.svg" />
        <File name="preloader" src="html/img/lightbox/preloader.gif" />
        <File name="01" src="html/img/overlays/01.png" />
        <File name="02" src="html/img/overlays/02.png" />
        <File name="03" src="html/img/overlays/03.png" />
        <File name="04" src="html/img/overlays/04.png" />
        <File name="05" src="html/img/overlays/05.png" />
        <File name="06" src="html/img/overlays/06.png" />
        <File name="07" src="html/img/overlays/07.png" />
        <File name="08" src="html/img/overlays/08.png" />
        <File name="09" src="html/img/overlays/09.png" />
        <File name="arrow_left" src="html/img/svg/arrow_left.svg" />
        <File name="arrow_right" src="html/img/svg/arrow_right.svg" />
        <File name="index" src="html/index.html" />
        <File name="bootstrap" src="html/js/bootstrap.js" />
        <File name="bootstrap.min" src="html/js/bootstrap.min.js" />
        <File name="jquery-3.2.1.min" src="html/js/jquery-3.2.1.min.js" />
        <File name="mdb" src="html/js/mdb.js" />
        <File name="mdb.min" src="html/js/mdb.min.js" />
        <File name="popper.min" src="html/js/popper.min.js" />
        <File name="mdb" src="html/sass/mdb.scss" />
        <File name="_custom" src="html/sass/mdb/_custom.scss" />
        <File name="_animations" src="html/sass/mdb/free/_animations.scss" />
        <File name="_badge" src="html/sass/mdb/free/_badge.scss" />
        <File name="_breadcrumb" src="html/sass/mdb/free/_breadcrumb.scss" />
        <File name="_buttons" src="html/sass/mdb/free/_buttons.scss" />
        <File name="_cards-basic" src="html/sass/mdb/free/_cards-basic.scss" />
        <File name="_carousel-basic" src="html/sass/mdb/free/_carousel-basic.scss" />
        <File name="_collapse" src="html/sass/mdb/free/_collapse.scss" />
        <File name="_deprecated" src="html/sass/mdb/free/_deprecated.scss" />
        <File name="_dropdowns" src="html/sass/mdb/free/_dropdowns.scss" />
        <File name="_footer" src="html/sass/mdb/free/_footer.scss" />
        <File name="_forms-basic" src="html/sass/mdb/free/_forms-basic.scss" />
        <File name="_global" src="html/sass/mdb/free/_global.scss" />
        <File name="_helpers" src="html/sass/mdb/free/_helpers.scss" />
        <File name="_jumbotron" src="html/sass/mdb/free/_jumbotron.scss" />
        <File name="_list-group" src="html/sass/mdb/free/_list-group.scss" />
        <File name="_masks" src="html/sass/mdb/free/_masks.scss" />
        <File name="_modals" src="html/sass/mdb/free/_modals.scss" />
        <File name="_msc" src="html/sass/mdb/free/_msc.scss" />
        <File name="_navbar" src="html/sass/mdb/free/_navbar.scss" />
        <File name="_pagination" src="html/sass/mdb/free/_pagination.scss" />
        <File name="_progress" src="html/sass/mdb/free/_progress.scss" />
        <File name="_tables" src="html/sass/mdb/free/_tables.scss" />
        <File name="_typography" src="html/sass/mdb/free/_typography.scss" />
        <File name="_waves" src="html/sass/mdb/free/_waves.scss" />
        <File name="_colors" src="html/sass/mdb/free/data/_colors.scss" />
        <File name="_functions" src="html/sass/mdb/free/data/_functions.scss" />
        <File name="_mixins" src="html/sass/mdb/free/data/_mixins.scss" />
        <File name="_prefixer" src="html/sass/mdb/free/data/_prefixer.scss" />
        <File name="_variables-b4" src="html/sass/mdb/free/data/_variables-b4.scss" />
        <File name="_variables" src="html/sass/mdb/free/data/_variables.scss" />
        <File name="Twitter_logo_blue" src="html/images/Twitter_logo_blue.png" />
        <File name="tapper" src="html/js/tapper.js" />
        <File name="error" src="html/error.html" />
        <File name="please_wait" src="html/images/please_wait.gif" />
        <File name="loading" src="html/images/loading.gif" />
        <File name="progressbar" src="html/css/progressbar.css" />
        <File name="__init__" src="lib/twitter/__init__.py" />
        <File name="ansi" src="lib/twitter/ansi.py" />
        <File name="api" src="lib/twitter/api.py" />
        <File name="archiver" src="lib/twitter/archiver.py" />
        <File name="auth" src="lib/twitter/auth.py" />
        <File name="cmdline" src="lib/twitter/cmdline.py" />
        <File name="corrupt" src="lib/twitter/corrupt.py" />
        <File name="follow" src="lib/twitter/follow.py" />
        <File name="ircbot" src="lib/twitter/ircbot.py" />
        <File name="logger" src="lib/twitter/logger.py" />
        <File name="oauth" src="lib/twitter/oauth.py" />
        <File name="oauth2" src="lib/twitter/oauth2.py" />
        <File name="oauth_dance" src="lib/twitter/oauth_dance.py" />
        <File name="stream" src="lib/twitter/stream.py" />
        <File name="stream_example" src="lib/twitter/stream_example.py" />
        <File name="timezones" src="lib/twitter/timezones.py" />
        <File name="twitter_globals" src="lib/twitter/twitter_globals.py" />
        <File name="util" src="lib/twitter/util.py" />
        <File name="camera" src="html/camera.html" />
        <File name="config" src="behavior_1/resource/config.json" />
        <File name="keyGoogleSTT" src="behavior_1/resource/keyGoogleSTT.json" />
        <File name="__init__" src="lib/apiclient/__init__.py" />
        <File name="__init__" src="lib/googleapiclient/__init__.py" />
        <File name="_auth" src="lib/googleapiclient/_auth.py" />
        <File name="channel" src="lib/googleapiclient/channel.py" />
        <File name="discovery" src="lib/googleapiclient/discovery.py" />
        <File name="__init__" src="lib/googleapiclient/discovery_cache/__init__.py" />
        <File name="appengine_memcache" src="lib/googleapiclient/discovery_cache/appengine_memcache.py" />
        <File name="base" src="lib/googleapiclient/discovery_cache/base.py" />
        <File name="file_cache" src="lib/googleapiclient/discovery_cache/file_cache.py" />
        <File name="errors" src="lib/googleapiclient/errors.py" />
        <File name="http" src="lib/googleapiclient/http.py" />
        <File name="mimeparse" src="lib/googleapiclient/mimeparse.py" />
        <File name="model" src="lib/googleapiclient/model.py" />
        <File name="sample_tools" src="lib/googleapiclient/sample_tools.py" />
        <File name="schema" src="lib/googleapiclient/schema.py" />
        <File name="__init__" src="lib/httplib2/__init__.py" />
        <File name="cacerts" src="lib/httplib2/cacerts.txt" />
        <File name="iri2uri" src="lib/httplib2/iri2uri.py" />
        <File name="socks" src="lib/httplib2/socks.py" />
        <File name="__init__" src="lib/oauth2client/__init__.py" />
        <File name="_helpers" src="lib/oauth2client/_helpers.py" />
        <File name="_openssl_crypt" src="lib/oauth2client/_openssl_crypt.py" />
        <File name="_pkce" src="lib/oauth2client/_pkce.py" />
        <File name="_pure_python_crypt" src="lib/oauth2client/_pure_python_crypt.py" />
        <File name="_pycrypto_crypt" src="lib/oauth2client/_pycrypto_crypt.py" />
        <File name="client" src="lib/oauth2client/client.py" />
        <File name="clientsecrets" src="lib/oauth2client/clientsecrets.py" />
        <File name="__init__" src="lib/oauth2client/contrib/__init__.py" />
        <File name="_appengine_ndb" src="lib/oauth2client/contrib/_appengine_ndb.py" />
        <File name="_metadata" src="lib/oauth2client/contrib/_metadata.py" />
        <File name="appengine" src="lib/oauth2client/contrib/appengine.py" />
        <File name="devshell" src="lib/oauth2client/contrib/devshell.py" />
        <File name="dictionary_storage" src="lib/oauth2client/contrib/dictionary_storage.py" />
        <File name="__init__" src="lib/oauth2client/contrib/django_util/__init__.py" />
        <File name="apps" src="lib/oauth2client/contrib/django_util/apps.py" />
        <File name="decorators" src="lib/oauth2client/contrib/django_util/decorators.py" />
        <File name="models" src="lib/oauth2client/contrib/django_util/models.py" />
        <File name="signals" src="lib/oauth2client/contrib/django_util/signals.py" />
        <File name="site" src="lib/oauth2client/contrib/django_util/site.py" />
        <File name="storage" src="lib/oauth2client/contrib/django_util/storage.py" />
        <File name="views" src="lib/oauth2client/contrib/django_util/views.py" />
        <File name="flask_util" src="lib/oauth2client/contrib/flask_util.py" />
        <File name="gce" src="lib/oauth2client/contrib/gce.py" />
        <File name="keyring_storage" src="lib/oauth2client/contrib/keyring_storage.py" />
        <File name="multiprocess_file_storage" src="lib/oauth2client/contrib/multiprocess_file_storage.py" />
        <File name="sqlalchemy" src="lib/oauth2client/contrib/sqlalchemy.py" />
        <File name="xsrfutil" src="lib/oauth2client/contrib/xsrfutil.py" />
        <File name="crypt" src="lib/oauth2client/crypt.py" />
        <File name="file" src="lib/oauth2client/file.py" />
        <File name="service_account" src="lib/oauth2client/service_account.py" />
        <File name="tools" src="lib/oauth2client/tools.py" />
        <File name="transport" src="lib/oauth2client/transport.py" />
        <File name="__init__" src="lib/pyasn1/__init__.py" />
        <File name="__init__" src="lib/pyasn1/codec/__init__.py" />
        <File name="__init__" src="lib/pyasn1/codec/ber/__init__.py" />
        <File name="decoder" src="lib/pyasn1/codec/ber/decoder.py" />
        <File name="encoder" src="lib/pyasn1/codec/ber/encoder.py" />
        <File name="eoo" src="lib/pyasn1/codec/ber/eoo.py" />
        <File name="__init__" src="lib/pyasn1/codec/cer/__init__.py" />
        <File name="decoder" src="lib/pyasn1/codec/cer/decoder.py" />
        <File name="encoder" src="lib/pyasn1/codec/cer/encoder.py" />
        <File name="__init__" src="lib/pyasn1/codec/der/__init__.py" />
        <File name="decoder" src="lib/pyasn1/codec/der/decoder.py" />
        <File name="encoder" src="lib/pyasn1/codec/der/encoder.py" />
        <File name="__init__" src="lib/pyasn1/codec/native/__init__.py" />
        <File name="decoder" src="lib/pyasn1/codec/native/decoder.py" />
        <File name="encoder" src="lib/pyasn1/codec/native/encoder.py" />
        <File name="__init__" src="lib/pyasn1/compat/__init__.py" />
        <File name="binary" src="lib/pyasn1/compat/binary.py" />
        <File name="calling" src="lib/pyasn1/compat/calling.py" />
        <File name="dateandtime" src="lib/pyasn1/compat/dateandtime.py" />
        <File name="integer" src="lib/pyasn1/compat/integer.py" />
        <File name="octets" src="lib/pyasn1/compat/octets.py" />
        <File name="string" src="lib/pyasn1/compat/string.py" />
        <File name="debug" src="lib/pyasn1/debug.py" />
        <File name="error" src="lib/pyasn1/error.py" />
        <File name="__init__" src="lib/pyasn1/type/__init__.py" />
        <File name="base" src="lib/pyasn1/type/base.py" />
        <File name="char" src="lib/pyasn1/type/char.py" />
        <File name="constraint" src="lib/pyasn1/type/constraint.py" />
        <File name="error" src="lib/pyasn1/type/error.py" />
        <File name="namedtype" src="lib/pyasn1/type/namedtype.py" />
        <File name="namedval" src="lib/pyasn1/type/namedval.py" />
        <File name="tag" src="lib/pyasn1/type/tag.py" />
        <File name="tagmap" src="lib/pyasn1/type/tagmap.py" />
        <File name="univ" src="lib/pyasn1/type/univ.py" />
        <File name="useful" src="lib/pyasn1/type/useful.py" />
        <File name="__init__" src="lib/pyasn1_modules/__init__.py" />
        <File name="pem" src="lib/pyasn1_modules/pem.py" />
        <File name="rfc1155" src="lib/pyasn1_modules/rfc1155.py" />
        <File name="rfc1157" src="lib/pyasn1_modules/rfc1157.py" />
        <File name="rfc1901" src="lib/pyasn1_modules/rfc1901.py" />
        <File name="rfc1902" src="lib/pyasn1_modules/rfc1902.py" />
        <File name="rfc1905" src="lib/pyasn1_modules/rfc1905.py" />
        <File name="rfc2251" src="lib/pyasn1_modules/rfc2251.py" />
        <File name="rfc2314" src="lib/pyasn1_modules/rfc2314.py" />
        <File name="rfc2315" src="lib/pyasn1_modules/rfc2315.py" />
        <File name="rfc2437" src="lib/pyasn1_modules/rfc2437.py" />
        <File name="rfc2459" src="lib/pyasn1_modules/rfc2459.py" />
        <File name="rfc2511" src="lib/pyasn1_modules/rfc2511.py" />
        <File name="rfc2560" src="lib/pyasn1_modules/rfc2560.py" />
        <File name="rfc3279" src="lib/pyasn1_modules/rfc3279.py" />
        <File name="rfc3280" src="lib/pyasn1_modules/rfc3280.py" />
        <File name="rfc3281" src="lib/pyasn1_modules/rfc3281.py" />
        <File name="rfc3412" src="lib/pyasn1_modules/rfc3412.py" />
        <File name="rfc3414" src="lib/pyasn1_modules/rfc3414.py" />
        <File name="rfc3447" src="lib/pyasn1_modules/rfc3447.py" />
        <File name="rfc3852" src="lib/pyasn1_modules/rfc3852.py" />
        <File name="rfc4210" src="lib/pyasn1_modules/rfc4210.py" />
        <File name="rfc4211" src="lib/pyasn1_modules/rfc4211.py" />
        <File name="rfc5208" src="lib/pyasn1_modules/rfc5208.py" />
        <File name="rfc5280" src="lib/pyasn1_modules/rfc5280.py" />
        <File name="sixm" src="lib/sixm.py" />
        <File name="rfc5652" src="lib/pyasn1_modules/rfc5652.py" />
        <File name="rfc6402" src="lib/pyasn1_modules/rfc6402.py" />
        <File name="__init__" src="lib/rsa/__init__.py" />
        <File name="_compat" src="lib/rsa/_compat.py" />
        <File name="_version133" src="lib/rsa/_version133.py" />
        <File name="_version200" src="lib/rsa/_version200.py" />
        <File name="asn1" src="lib/rsa/asn1.py" />
        <File name="bigfile" src="lib/rsa/bigfile.py" />
        <File name="cli" src="lib/rsa/cli.py" />
        <File name="common" src="lib/rsa/common.py" />
        <File name="core" src="lib/rsa/core.py" />
        <File name="key" src="lib/rsa/key.py" />
        <File name="parallel" src="lib/rsa/parallel.py" />
        <File name="pem" src="lib/rsa/pem.py" />
        <File name="pkcs1" src="lib/rsa/pkcs1.py" />
        <File name="prime" src="lib/rsa/prime.py" />
        <File name="randnum" src="lib/rsa/randnum.py" />
        <File name="transform" src="lib/rsa/transform.py" />
        <File name="util" src="lib/rsa/util.py" />
        <File name="varblock" src="lib/rsa/varblock.py" />
        <File name="__init__" src="lib/uritemplate/__init__.py" />
        <File name="api" src="lib/uritemplate/api.py" />
        <File name="template" src="lib/uritemplate/template.py" />
        <File name="variable" src="lib/uritemplate/variable.py" />
    </Resources>
    <Topics />
    <IgnoredPaths />
    <Translations auto-fill="en_US">
        <Translation name="translation_en_US" src="translations/translation_en_US.ts" language="en_US" />
        <Translation name="translation_ja_JP" src="translations/translation_ja_JP.ts" language="ja_JP" />
    </Translations>
</Package>
